minimum_pre_commit_version: 2.4.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: trailing-whitespace # Trims trailing whitespace.
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.

  # ----- Formatting ---------------------------------------------------------------------------->

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [-l 100]
